if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'airblade/vim-gitgutter'
Plug 'andrewradev/splitjoin.vim'
Plug 'christianrondeau/vim-base64'
Plug 'ervandew/supertab'
Plug 'fatih/vim-hclfmt'
Plug 'jiangmiao/auto-pairs'
Plug 'junegunn/vim-easy-align'
Plug 'kien/ctrlp.vim'
Plug 'ntpeters/vim-better-whitespace'
Plug 'rking/ag.vim'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/syntastic'
Plug 'terryma/vim-multiple-cursors'
Plug 'tomasr/molokai'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-endwise' " end certain structures automatically
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-surround'
Plug 'vim-scripts/bash-support.vim'
Plug 'vim-scripts/matchit.zip'
Plug 'w0rp/ale'          " async linter


" https://vimawesome.com/plugin/fugitive-vim
" https://vimawesome.com/plugin/the-nerd-commenter

" Plug 'hashivim/vim-terraform'
" Plug 'easymotion/vim-easymotion'
" Plug 'nathanaelkane/vim-indent-guides'

call plug#end()

source ~/.vimrc.after
